In [3]:
class A:
    def rk(self):
        print("in class a")
class B:
    def rk(self):
        print("in class b")
class C:
    def rk(self):
        print("in class c")
class D(B,C):
    pass
    
r=D()
r.rk()
print(D.mro)

in class b
<built-in method mro of type object at 0x0000015A7B1EBC10>


In [4]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p2):
    pass
class c2(p2):
    def bar(self):
        print("bar from p2")
class gc(c1,c2):
    pass

g=gc()
g.foo()
g.bar()


foo from p2
bar from p2


In [8]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p1,p2):
    def bar(self):
        print("bar from p2")
class gc(c1,c2):
    pass

g=gc()
g.foo()
g.bar()


foo from p1
bar from p2


In [9]:
class p1:
    def foo(self):
        print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p2,p1):
    def bar(self):
        print("bar from p2")
class gc(c1,c2):
    pass

g=gc()
g.foo()
g.bar()


TypeError: Cannot create a consistent method resolution
order (MRO) for bases p1, p2

In [14]:
class a:
    pass
class b:
    pass
class c:
    pass
class d:
    pass
class e:
    pass
class k1(c,a,b):
    pass
class k3(b,d):
    pass
class k2(a,d,e):
    pass
class z(k1,k3,k2):
    pass
print(z.mro())

[<class '__main__.z'>, <class '__main__.k1'>, <class '__main__.c'>, <class '__main__.k3'>, <class '__main__.k2'>, <class '__main__.a'>, <class '__main__.b'>, <class '__main__.d'>, <class '__main__.e'>, <class 'object'>]


In [17]:
# abstract class 

from abc import ABC, abstractmethod 

class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
        
    @abstractmethod
    def draw(self):
        pass

class circle(shape):
    def __init__(self):
        super().__init__("circle")
        
    def draw(self):
        print("Drawing a circle")

c=circle()
c.draw()

Drawing a circle


In [31]:
from abc import ABC,abstractmethod
class Staff(ABC):
    
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
        
    @abstractmethod   
    def display(self):
        print("Name :",self.name)
        print("Salary :",self.salary)
        
class Teaching(Staff):
    
    def __init__(self,name,salary,subject):
        super().__init__(name,salary)
        self.subject=subject
      
    def display(self):
        print("Name :",self.name)
        print("Salary :",self.salary)
        print("Subject :",self.subject)
        
class Nm_teaching(Staff):
    
    def __init__(self,name,salary,dept):
        super().__init__(name,salary)
        self.dept=dept
        
    def display(self):
        print("Name :",self.name)
        print("Salary :",self.salary)
        print("Dept :",self.dept)
        
t=Teaching("a",2000,"pht")
t.display()

  

Name : a
Salary : 2000
Subject : pht


In [ ]:
# create class called student having name and email as its data member and put data as the init function should assign the value
# as its parameter and the put data function should display the data of studetn create another class claeed phdguide having name
# email and students as its data member here the student variable is the list of student another the guid the phdguide class
# should having 4 bound method init,putdata,add and remove

class Student:
    
    def __init__(self,name,email):
        self.name=name
        self.email=email
        
    def display(self):
        print("Name :",self.name)
        print("Email :",self.email)

class phdguide(Student):
    s=[]
    
    def __init__(self,name,email):
        super().__init__(name,email)
        

In [ ]:
# create a class student with a following attributes rollno,name,age,totalmarks crate suitable methods for reading and printing 
# members varibale wap to overload == operator to print the details of student having same marks



In [4]:
# Numpy
# - numerical python
# - python libarary used for working with arrays
# - list that serves the purpose of arrays but also to process
# - numpy aims to provide an array object that is upto 50x faster than traditional python list

import numpy as np
import sys

s=range(1000)
print("Size of each element of list in bytes:",sys.getsizeof(s))
print("Size of whole list in bytes:",sys.getsizeof(s)*len(s))

d=np.arange(1000)
print("Size of each element of numpy array in bytes:",d.itemsize)
print("Size of whole element of numpy array in bytes:",d.itemsize*d.size)

Size of each element of list in bytes: 48
Size of whole list in bytes: 48000
Size of each element of numpy array in bytes: 4
Size of whole element of numpy array in bytes: 4000


In [6]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)
print(type(arr))

[1 2 3 4]
1
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[3])
print(arr[2]+arr[4]) #3+5

4
8


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[3])
print(arr[2]+arr[4]) #3+5

2
6
4
7


In [13]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])
print(arr[0,-3])
print(arr[1,0:3]) # if one slicing is used then two dimensiojn is used
print(arr[0:2,2]) # if one slicing is used then two dimensiojn is used
print(arr[1:2,0:3]) # if two slicing is used then two dimensiojn is used


8
2
[5 6 7]
[3 7]
[[5 6 7]]


In [15]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1.ndim) # it tells dimension
print(arr1.shape) # it tells rows and cols

print(arr2.ndim) # it tells dimension
print(arr2.shape) # it tells rows and cols

print(arr3.ndim) # it tells dimension
print(arr3.shape) # it tells rows and cols

1
(5,)
2
(2, 4)
3
(2, 2, 3)


In [16]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
newarr=arr1.reshape(2,3) 
# karan k jyre apde reshape kav v tyre j rete apde repshape kar v atla element apda juna array ma hova joi

ValueError: cannot reshape array of size 5 into shape (2,3)

In [21]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
newarr=arr1.reshape(2,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [22]:
# Iteration

arr=np.array([[[1,2,3,4,5]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5


In [23]:
# nditer

arr=np.array([[[1,2,3,4,5]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5


In [26]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:,1::2]):
    print(x)
    

2
4
6
8


In [47]:
# built in function 

# 1. concatenate

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9,10])

arr= np.concatenate((arr1,arr2,arr3))
print(arr)
print()

arr4 = np.array([[1,2],[3,4]])
arr5 = np.array([[5,6],[7,8]])

arr6= np.concatenate((arr4,arr5))
print(arr6)
print()

# 2. split

import numpy as np

arr=np.array([1,2,3,4])
newarr=np.array_split(arr,4)
print(newarr)

arr=np.array([1,2,3,4])
newarr=np.array_split(arr,3)
print(newarr)

arr=np.array([1,2,3,4])
newarr=np.array_split(arr,2)
print(newarr)

arr=np.array([1,2,3,4])
newarr=np.array_split(arr,1)
print(newarr)

arr7=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr,4)
print(newarr)

arr7=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr,4,axis=1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([1]), array([2]), array([3]), array([4])]
[array([1, 2]), array([3]), array([4])]
[array([1, 2]), array([3, 4])]
[array([1, 2, 3, 4])]
[array([1]), array([2]), array([3]), array([4])]


IndexError: tuple index out of range

In [49]:
# 3. where

import numpy as np
arr=np.array([1,2,3,4,5,6])
x=np.where(arr==4)
print(x)

arr=np.array([[1,2],[2,3],[4,5],[6,7]])
x=np.where(arr==4)
print(x)

(array([3], dtype=int64),)
(array([2], dtype=int64), array([0], dtype=int64))
